sudo: false
language: cpp
compiler:
  - gcc
  - clang

cache: ccache

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

addons:
  apt:
    packages:
    - cmake
    - libboost-dev                                                                                                                                                    
    - bison 
    - flex                                                                                                                                                      
    - libglib2.0-dev                                                                                                                                                  
    - libncurses5-dev  

before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../esesc -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script: 
  - make
  - make check

after_script:
  - mkdir run
  - cd run
  - cp ../../esesc/conf/* .
  - cp ../../esesc/bins/* .
  - ../main/esesc

